stages:
  - prepare
  - lint
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  PYTHONPATH: "$CI_PROJECT_DIR"

# Common setup for all jobs
.setup-python:
  image: python:3.13
  before_script:
    - source .venv/bin/activate
  # Cache dependencies between jobs
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - .pip-cache/
      - .venv/

prepare:
  stage: prepare
  extends: .setup-python
  before_script: [ ]
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -e ".[dev]"
  cache:
    policy: push
  needs: [ ]

# Linting jobs
black:
  stage: lint
  extends: .setup-python
  script:
    - black --check --diff --color src/ test/
  allow_failure: true
  needs:
    - prepare

isort:
  stage: lint
  extends: .setup-python
  script:
    - isort --check --diff --color src/ test/
  allow_failure: true
  needs:
    - prepare

mypy:
  stage: lint
  extends: .setup-python
  script:
    - mypy --install-types src/ test/
    - mypy --color-output --junit-xml=mypy-report.xml src/ test/
  allow_failure: true
  artifacts:
    reports:
      codequality: mypy-report.xml
  needs:
    - prepare

# Test job
pytest:
  stage: test
  extends: .setup-python
  script:
    - pytest --cov=src/bluebeacon --cov-report=xml:coverage.xml --cov-report=term --junitxml=junit.xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: junit.xml
  needs:
    - black
    - isort
    - mypy